name: alice_get_connect
description: A Flutter library that enables seamless integration between alice, and get_connect from GetX.
version: 1.1.0
homepage: https://github.com/teknologicakrainternasional/alice_get_connect

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  alice:
    git:
      url: https://github.com/husainazkas/alice.git
      ref: enhancement/separate-between-android-notif-small-and-large-icoon
      path: packages/alice
  get: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: