name: alice_get_connect
description: A Flutter library that enables seamless integration between alice, and get_connect from GetX.
version: 1.1.0
homepage: https://github.com/teknologicakrainternasional/alice_get_connect

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  alice: ^1.0.0
  get: ^5.0.0-release-candidate-9.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: